version: "0.1"

services:
  auralarchive:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: auralarchive:dev
    container_name: auralarchive
    command: python app.py
    user: "1000:1000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - LOG_FILE=auralarchive_web.log
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "5000:5000"
    volumes:
      - /media/MS_Server/Home_Server/config/auralarchive:/app
      - /media/MS_Server/Home_Server/config/auralarchive/logs:/app/logs
      - /media/MS_TV2/Audiobooks/Library:/audiobooks
      - /media/MS_Server/Downloads:/downloads
    stdin_open: true
    tty: true
    restart: unless-stopped
  
